{{ if .Values.configmaps }}
{{ range .Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{ range $key, $value := .data }}
  {{ $key }}: {{ $value | toJson | quote | indent 4 }}
  {{ end }}
{{ end }}
{{ end }}