apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.service.annotations  | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: app-http-port
    {{- range .Values.service.secondaryPorts }}
    - name: {{ .name | default (print "port-" .port) }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}

